Repository ipf-dev/ipf-homepage-new, pull requests merged in 2022-07, with the labels that each got.

#46 Package updateConfig [] `@tapas/ui` 대신 `@ipf-dev/web-spindle-design-system` 사용
  .npmrc
  package-lock.json
  package.json
  src/components/Pagination.style.ts
  src/components/Pagination.tsx
  src/layouts/theme.ts
  src/pages/news.tsx
  yarn.lock
Labels: ⚙️ setting

#47 Implement [IPFHOME-73] 2021, 2022년 연혁 추가
  src/locales/en/translation.json
  src/locales/ko/translation.json
  src/sections/About/HistorySection.tsx
Labels: ✨ feature

#48 Fix [IPFHOME-73] 오타 수정
  src/locales/en/translation.json
Labels: 🙅‍♀️ DO NOT REVIEW

#49 Config [] cd 깃헙 액션 추가
  .github/workflow/cd.yml
Labels: ⚙️ setting

#50 Implement [IPFHOME-72] 우리가 일하는 방법 링크 변경
  src/components/FloatingButton.tsx
Labels: ✨ feature

#52 Docs [] 배포시 발생할 수 있는 인증 실패 문제 해결 내용을 README에 추가
  README.md
Labels: documentation
